[project]
name = "pandasql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "psycopg2>=2.9.10",
    "skimpy>=0.0.18",
    "sqlalchemy>=2.0.38",
    "sqlalchemy-schemadisplay>=2.0",
]
